name: test-pull-request

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./
        run: dotnet restore

      - name: Build
        working-directory: ./
        run: dotnet build --no-restore --configuration Release

      - name: Test
        working-directory: ./
        run: dotnet test --no-build --verbosity normal --configuration Release